export type StudentJob = {
  id: string;
  title: string;
  company_name?: string | null;
  corporate_name?: string | null;
  location?: string | string[] | null;
  job_type?: string | null;
  salary_min?: number | null;
  salary_max?: number | null;
  salary_currency?: string | null;
  application_deadline?: string | null;
  description?: string | null;
  requirements?: string | null;
  responsibilities?: string | null;
  industry?: string | null;
  skills_required?: string[] | null;
  experience_min?: number | null;
  experience_max?: number | null;
  created_at?: string | null;
  can_apply?: boolean;
  application_status?: string | null;
  status?: string | null;
  remote_work?: boolean | null;
  travel_required?: boolean | null;
  onsite_office?: boolean | null;
  mode_of_work?: string | null;
  education_level?: string | string[] | null;
  education_degree?: string | string[] | null;
  education_branch?: string | string[] | null;
  max_applications?: number | null;
  current_applications?: number | null;
  selection_process?: string | null;
  campus_drive_date?: string | null;
  views_count?: number | null;
  applications_count?: number | null;
  corporate_id?: string | null;
  is_active?: boolean | null;
  number_of_openings?: number | null;
  perks_and_benefits?: string | null;
  eligibility_criteria?: string | null;
  service_agreement_details?: string | null;
  expiration_date?: string | null;
  ctc_with_probation?: string | null;
  ctc_after_probation?: string | null;
  company_logo?: string | null;
  company_website?: string | null;
  company_address?: string | null;
  company_size?: string | null;
  company_type?: string | null;
  company_founded?: number | null;
  company_description?: string | null;
  contact_person?: string | null;
  contact_designation?: string | null;
};

export type StudentApplication = {
  id: string;
  job_id: string;
  job_title?: string | null;
  company_name?: string | null;
  corporate_name?: string | null;
  status: string;
  applied_at?: string | null;
  updated_at?: string | null;
  interview_date?: string | null;
  offer_letter_url?: string | null;
};
